# Generated by Django 4.1.3 on 2022-11-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='creationdate',
            new_name='creation_date',
        ),
    ]
